# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.define :batho_server do |batho_server|
        batho_server.vm.box = "freebsd/FreeBSD-12.2-STABLE"
        batho_server.vm.network "private_network", ip: "192.168.55.10"
        batho_server.vm.hostname = "vagrant.batho.server"
    end

    config.vm.define :motsamaisi_server do |motsamaisi_server|
        motsamaisi_server.vm.box = "freebsd/FreeBSD-12.2-STABLE"
        motsamaisi_server.vm.network "private_network", ip: "192.168.55.11"
        motsamaisi_server.vm.hostname = "vagrant.motsamaisi.server"
    end

    config.vm.define :db do |db|
        db.vm.box = "freebsd/FreeBSD-12.2-STABLE"
        db.vm.network "private_network", ip: "192.168.55.12"
        db.vm.hostname = "vagrant.db.server"
    end


end
