pub enum DeliveryType{}
pub struct Vehicle{}
pub enum VehicleType{}
pub struct DeliveryFee{}
pub struct Delivery{}
pub struct Taxi{}
pub struct Scooter{}
pub struct Route{}
pub struct DeliveryVehicle{}
pub struct CourierUser{}
pub struct Driver{}
pub struct Fees{}
pub enum DeliveryStatus{}
pub struct VehicleRegistration{}
pub struct VehicleCapacity{}
pub enum VehicleCapacityStatus{}
pub enum VehicleStatus{}
pub struct VehicleDimensions{}